"""Users table

Revision ID: 047548ff3045
Revises: ee31c09ec212
Create Date: 2025-08-12 16:14:38.082837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047548ff3045'
down_revision = 'ee31c09ec212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plex_baseurl', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('plex_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plex_token')
        batch_op.drop_column('plex_baseurl')

    # ### end Alembic commands ###
